-- Phone Center product database and seed data
-- Run from a terminal with: mysql -u root -p < products_insert.sql
-- Safe to run repeatedly: existing product IDs are updated.

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS `phone`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE `phone`;

CREATE TABLE IF NOT EXISTS `products` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(3) NULL,
  `updated_at` DATETIME(3) NULL,
  `deleted_at` DATETIME(3) NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` BIGINT NOT NULL,
  `spec` TEXT NULL,
  `image` VARCHAR(1024) NULL,
  `category` VARCHAR(100) NULL,
  `badge` VARCHAR(100) NULL,
  `colors` JSON NULL,
  `storage_options` JSON NULL,
  `ram_options` JSON NULL,
  `region` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_products_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

START TRANSACTION;
-- record id=1 (source data.js lines 5-17)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (1, 'iPhone 17 Pro Max (نارنجی)', 420000000, '256GB | 12GB RAM | ZAA', '/assets/images/iphone 17 promax  zaa 256 oraing.webp', 'iphone', 'پرفروش', '["نارنجی","سفید","آبی تیره"]', '["256GB","512GB","1TB"]', '["12GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=2 (source data.js lines 18-30)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (2, 'iPhone 17 Pro Max (سفید)', 415000000, '256GB | 12GB RAM | ZAA', '/assets/images/iphone 17 promax  zaa 256 white.webp', 'iphone', 'جدید', '["سفید","نارنجی","آبی تیره"]', '["256GB","512GB"]', '["12GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=3 (source data.js lines 31-43)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (3, 'iPhone 17 Pro Max (آبی تیره)', 418000000, '256GB | 12GB RAM | CH', '/assets/images/iphone 17 promax  zaa 256 blue.webp', 'iphone', '', '["آبی تیره","سفید","نارنجی"]', '["256GB","512GB"]', '["12GB"]', 'CH') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=4 (source data.js lines 44-56)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (4, 'iPhone 17 Pro Max (سفید 512GB)', 450000000, '512GB | 12GB RAM | LLA', '/assets/images/iphone 17 promax  zaa 256 white.webp', 'iphone', '', '["سفید"]', '["512GB"]', '["12GB"]', 'LLA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=5 (source data.js lines 57-69)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (5, 'iPhone 17 Pro (آبی تیره)', 350000000, '128GB | 12GB RAM | ZAA', '/assets/images/iphone 17 promax  zaa 256 blue.webp', 'iphone', '', '["طوسی","سفید"]', '["128GB","256GB"]', '["12GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=6 (source data.js lines 70-82)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (6, 'iPhone 17 Pro (سفید)', 390000000, '256GB | 12GB RAM | ZAA', '/assets/images/iphone 17 promax  zaa 256 white.webp', 'iphone', '', '["سفید","طوسی"]', '["256GB","512GB"]', '["12GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=7 (source data.js lines 83-95)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (7, 'iPhone 17 (آبی)', 280000000, '256GB | 8GB RAM | CH', '/assets/images/17 normal blue 256 ch.webp', 'iphone', '', '["صورتی","سبز","آبی"]', '["128GB","256GB"]', '["8GB"]', 'CH') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=8 (source data.js lines 96-108)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (8, 'iPhone 17 (سبز)', 275000000, '256GB | 8GB RAM | LLA', '/assets/images/17 normal green 256 lla.webp', 'iphone', '', '["سبز","صورتی"]', '["128GB"]', '["8GB"]', 'LLA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=9 (source data.js lines 109-121)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (9, 'iPhone 16 Pro Max (مشکی)', 350000000, '256GB | 8GB RAM | ZAA', '/assets/images/16 promax black 256 zaa.webp', 'iphone', '', '["طوسی","سفید","آبی"]', '["256GB","512GB"]', '["8GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=10 (source data.js lines 122-134)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (10, 'iPhone 16 Pro (سفید)', 280000000, '128GB | 8GB RAM | CH', '/assets/images/iPhone 16 Pro ZAA.webp', 'iphone', '', '["سفید","طوسی"]', '["128GB","256GB"]', '["8GB"]', 'CH') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=11 (source data.js lines 135-147)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (11, 'iPhone 16 (آبی)', 220000000, '128GB | 6GB RAM | CH', '/assets/images/16 normal blue 256 ch.webp', 'iphone', '', '["آبی","صورتی","سبز"]', '["128GB","256GB"]', '["6GB"]', 'CH') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=12 (source data.js lines 148-160)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (12, 'iPhone 15 (آبی)', 150000000, '128GB | 6GB RAM | CH', '/assets/images/15 normal blue 256 ch.webp', 'iphone', 'اقتصادی', '["سفید","مشکی","قرمز"]', '["128GB"]', '["6GB"]', 'CH') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=13 (source data.js lines 161-173)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (13, 'iPhone 15 Pro Max (مشکی)', 300000000, '256GB | 8GB RAM | ZAA', '/assets/images/15 promax 256 zaa.webp', 'iphone', '', '["طوسی","سفید","آبی"]', '["256GB","512GB"]', '["8GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=14 (source data.js lines 174-186)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (14, 'iPhone 15 (صورتی)', 200000000, '128GB | 6GB RAM | CH', '/assets/images/15 normal pink 256 ch.webp', 'iphone', '', '["صورتی","سبز","آبی"]', '["128GB","256GB"]', '["6GB"]', 'CH') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=15 (source data.js lines 187-199)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (15, 'iPhone 14 Pro Max (بنفش)', 250000000, '256GB | 6GB RAM | LAA', '/assets/images/14 promax', 'iphone', '', '["طوسی","سفید","طلایی"]', '["256GB","512GB"]', '["6GB"]', 'LLA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=16 (source data.js lines 202-214)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (16, 'Samsung Galaxy S26 Ultra', 450000000, '512GB | 12GB RAM | Vietnam', '/assets/images/s26 ulta 256 vet.webp', 'samsung', 'جدید', '["مشکی","سفید","بنفش"]', '["512GB","1TB"]', '["12GB","16GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=17 (source data.js lines 215-227)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (17, 'Samsung Galaxy S25 Ultra', 380000000, '256GB | 12GB RAM | Vietnam', '/assets/images/s25 ultra 256 vet.webp', 'samsung', 'پرفروش', '["مشکی","سفید","سبز"]', '["256GB","512GB"]', '["12GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=18 (source data.js lines 228-240)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (18, 'Samsung Galaxy S25+', 300000000, '256GB | 12GB RAM | Vietnam', '/assets/images/s25 plus', 'samsung', '', '["مشکی","سفید","صورتی"]', '["256GB","512GB"]', '["12GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=19 (source data.js lines 241-253)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (19, 'Samsung Galaxy S25', 250000000, '128GB | 8GB RAM | Vietnam', '/assets/images/Samsung-Galaxy-S25.jpg', 'samsung', '', '["مشکی","سفید","آبی"]', '["128GB","256GB"]', '["8GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=21 (source data.js lines 254-266)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (21, 'Samsung Galaxy A56', 140000000, '256GB | 8GB RAM | Vietnam', '/assets/images/a56 256 vet.webp', 'samsung', '', '["مشکی","سفید","بنفش"]', '["128GB","256GB"]', '["8GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=22 (source data.js lines 267-279)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (22, 'Samsung Galaxy A36', 100000000, '256GB | 6GB RAM | Vietnam', '/assets/images/a36 256 vet.webp', 'samsung', '', '["مشکی","سفید","آبی"]', '["256GB"]', '["6GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=23 (source data.js lines 280-292)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (23, 'Samsung Galaxy A17', 65000000, '256GB | 8GB RAM | Vietnam', '/assets/images/a17 256 vet.webp', 'samsung', '', '["مشکی","سفید"]', '["128GB","64GB"]', '["4GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=24 (source data.js lines 293-305)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (24, 'Samsung Galaxy Z Fold 7', 550000000, '256GB | 12GB RAM | Vietnam', '/assets/images/zfold 7', 'samsung', 'پرچمدار', '["مشکی","سفید","آبی"]', '["512GB","1TB"]', '["12GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=25 (source data.js lines 306-318)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (25, 'Samsung Galaxy Z Flip 6', 400000000, '256GB | 8GB RAM | Vietnam', '/assets/images/zflip 6', 'samsung', '', '["صورتی","آبی","سبز"]', '["256GB","512GB"]', '["8GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=26 (source data.js lines 319-331)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (26, 'Samsung Galaxy A26', 85000000, '256GB | 8GB RAM | Vietnam', '/assets/images/a26.webp', 'samsung', '', '["مشکی","سفید"]', '["128GB","64GB"]', '["6GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=27 (source data.js lines 332-344)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (27, 'Samsung Galaxy A07', 120000000, '128GB | 6GB RAM | Vietnam', '/assets/images/a07.webp', 'samsung', '', '["مشکی","سبز"]', '["128GB","256GB"]', '["6GB","8GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=28 (source data.js lines 347-359)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (28, 'Xiaomi 15T Pro', 320000000, '1T | 12GB RAM | Global', '/assets/images/15 t pro.webp', 'xiaomi', 'پرفروش', '["مشکی","سفید","سبز"]', '["512GB","1TB"]', '["16GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=29 (source data.js lines 360-372)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (29, 'Xiaomi Redmi note 14 pro', 85000000, '256GB | 8GB RAM | Global', '/assets/images/Redmi Note 14 Pro 4G.webp', 'xiaomi', '', '["مشکی","سفید","صورتی"]', '["256GB","512GB"]', '["8GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=30 (source data.js lines 373-385)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (30, 'Xiaomi Poco X8 Pro', 200000000, '512GB | 12GB RAM | Global', '/assets/images/poco x8 pro.webp', 'xiaomi', '', '["مشکی","سفید","آبی"]', '["256GB","512GB"]', '["12GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=31 (source data.js lines 386-398)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (31, 'Xiaomi Redmi Note 15 Pro', 130000000, '512GB | 12GB RAM | Global', '/assets/images/Redmi Note 15 Pro 4G.webp', 'xiaomi', '', '["مشکی","سفید","بنفش"]', '["256GB","512GB"]', '["8GB","12GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=32 (source data.js lines 399-411)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (32, 'Xiaomi Redmi Note 15', 85000000, '256GB | 8GB RAM | Global', '/assets/images/note 15.webp', 'xiaomi', '', '["مشکی","سفید","سبز"]', '["128GB","256GB"]', '["6GB","8GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=33 (source data.js lines 412-424)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (33, 'Xiaomi Poco X7 Pro', 140000000, '512GB | 12GB RAM | Global', '/assets/images/poco x7pro.webp', 'xiaomi', '', '["مشکی","سفید","زرد"]', '["256GB","512GB"]', '["12GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=34 (source data.js lines 425-437)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (34, 'Xiaomi Poco M8 Pro', 80000000, '512GB | 12GB RAM | Global', '/assets/images/m6pro.webp', 'xiaomi', '', '["مشکی","سفید"]', '["128GB","256GB"]', '["6GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=35 (source data.js lines 438-450)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (35, 'Xiaomi Poco M8', 180000000, '256GB | 8GB RAM | Global', '/assets/images/m8.webp', 'xiaomi', '', '["مشکی","سفید"]', '["256GB","512GB"]', '["12GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=36 (source data.js lines 451-463)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (36, 'Xiaomi Poco C75', 50000000, '256GB | 8GB RAM | Global', '/assets/images/poco c71.webp', 'xiaomi', 'اقتصادی', '["مشکی","سفید","آبی"]', '["128GB","64GB"]', '["4GB","6GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=38 (source data.js lines 466-477)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`) VALUES (38, 'iPad Pro M5 13"', 550000000, '2T | 16GB | WiFi', '/assets/images/tablet m5 pro.webp', 'tablet', '', '["طوسی","سفید"]', '["512GB","1TB","2TB"]', '["8GB","16GB"]') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`);
-- record id=39 (source data.js lines 478-489)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`) VALUES (39, 'iPad Pro M5 11"', 450000000, '256GB | 12GB | WiFi', '/assets/images/ipad pro m5 11.webp', 'tablet', 'پرفروش', '["طوسی","سفید"]', '["256GB","512GB","1TB"]', '["8GB","16GB"]') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`);
-- record id=40 (source data.js lines 490-501)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`) VALUES (40, 'iPad Air M3 13"', 380000000, '128GB | 8GB | WiFi', '/assets/images/ipad air m3.webp', 'tablet', '', '["طوسی","سفید","صورتی"]', '["256GB","512GB"]', '["8GB"]') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`);
-- record id=41 (source data.js lines 502-514)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (41, 'iPad 10th Gen', 220000000, '64GB | WiFi | ZAA', '/assets/images/ipad10th.webp', 'tablet', '', '["سفید","آبی","صورتی"]', '["64GB","256GB"]', '["4GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=42 (source data.js lines 515-527)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (42, 'Samsung Tab S9 Ultra', 420000000, '256GB | 12GB RAM | Vietnam', '/assets/images/tabs9ultra.webp', 'tablet', '', '["مشکی","سفید"]', '["256GB","512GB"]', '["12GB","16GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=43 (source data.js lines 528-540)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (43, 'Samsung Tab S9+', 320000000, '256GB | 12GB RAM | Vietnam', '/assets/images/tabs9plus.webp', 'tablet', '', '["مشکی","سفید"]', '["256GB","512GB"]', '["12GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=44 (source data.js lines 541-553)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (44, 'Xiaomi Pad 6', 180000000, '128GB | 6GB RAM | Global', '/assets/images/xiaomipad6.webp', 'tablet', '', '["طوسی","سفید","آبی"]', '["128GB","256GB"]', '["6GB","8GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=45 (source data.js lines 554-566)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (45, 'Xiaomi Pad 5', 140000000, '128GB | 6GB RAM | Global', '/assets/images/xiaomipad5.webp', 'tablet', '', '["طوسی","سفید"]', '["128GB","256GB"]', '["6GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=46 (source data.js lines 569-581)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (46, 'MacBook Pro M3 14"', 620000000, '512GB | 16GB RAM | ZAA', '/assets/images/macbookpro_m3_14.webp', 'macbook', 'جدید', '["طوسی","سفید"]', '["512GB","1TB","2TB"]', '["16GB","36GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=47 (source data.js lines 582-594)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (47, 'MacBook Pro M3 16"', 750000000, '1TB | 36GB RAM | CH', '/assets/images/macbookpro_m3_16.webp', 'macbook', '', '["طوسی","سفید"]', '["1TB","2TB"]', '["36GB","48GB"]', 'CH') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=48 (source data.js lines 595-607)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (48, 'MacBook Air M3 13"', 480000000, '256GB | 8GB RAM | LLA', '/assets/images/macbookair_m3_13.webp', 'macbook', '', '["طوسی","سفید","طلایی"]', '["256GB","512GB","1TB"]', '["8GB","16GB"]', 'LLA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=49 (source data.js lines 608-620)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (49, 'MacBook Air M3 15"', 530000000, '256GB | 8GB RAM | ZAA', '/assets/images/macbookair_m3_15.webp', 'macbook', '', '["طوسی","سفید","طلایی"]', '["256GB","512GB","1TB"]', '["8GB","16GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=50 (source data.js lines 621-633)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (50, 'MacBook Pro M2 14"', 550000000, '512GB | 16GB RAM | Vietnam', '/assets/images/macbookpro_m2_14.webp', 'macbook', '', '["طوسی","سفید"]', '["512GB","1TB"]', '["16GB","32GB"]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=51 (source data.js lines 634-646)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (51, 'MacBook Air M2 13"', 400000000, '256GB | 8GB RAM | ZAA', '/assets/images/macbookair_m2_13.webp', 'macbook', '', '["طوسی","سفید","طلایی"]', '["256GB","512GB"]', '["8GB","16GB"]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=52 (source data.js lines 649-661)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (52, 'AirPods Pro 2 (USB-C)', 26000000, 'نسل دوم | ZAA', '/assets/images/airpodspro2.webp', 'accessory', 'پرفروش', '["سفید"]', '[]', '[]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=53 (source data.js lines 662-674)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (53, 'AirPods 4', 18000000, 'نسل چهارم | CH', '/assets/images/airpods4.webp', 'accessory', '', '["سفید"]', '[]', '[]', 'CH') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=54 (source data.js lines 675-687)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (54, 'Samsung Buds 3 Pro', 22000000, 'بیسیم | Vietnam', '/assets/images/buds3pro.webp', 'accessory', '', '["سفید","مشکی"]', '[]', '[]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=55 (source data.js lines 688-700)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (55, 'Xiaomi Band 8 Pro', 9500000, 'نوار سلامت | Global', '/assets/images/band8pro.webp', 'accessory', '', '["مشکی","سفید","آبی"]', '[]', '[]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=56 (source data.js lines 701-713)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (56, 'Apple Watch Ultra 2', 150000000, '49mm | ZAA', '/assets/images/watchultra2.webp', 'accessory', '', '["طوسی","سفید"]', '[]', '[]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=57 (source data.js lines 714-726)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (57, 'Galaxy Watch 6 Classic', 95000000, '47mm | Vietnam', '/assets/images/watch6classic.webp', 'accessory', '', '["مشکی","سفید"]', '[]', '[]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=58 (source data.js lines 727-739)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (58, 'Xiaomi Watch S3', 50000000, '46mm | Global', '/assets/images/watchs3.webp', 'accessory', '', '["مشکی","سفید","طلایی"]', '[]', '[]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=59 (source data.js lines 740-752)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (59, 'Beats Fit Pro', 28000000, 'بیسیم | ZAA', '/assets/images/beatsfitpro.webp', 'accessory', '', '["سفید","مشکی","بنفش"]', '[]', '[]', 'ZAA') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=60 (source data.js lines 753-765)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (60, 'JBL Tune 770NC', 22000000, 'هدفون | Global', '/assets/images/jbl770nc.webp', 'accessory', '', '["مشکی","سفید","آبی"]', '[]', '[]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=61 (source data.js lines 766-778)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (61, 'Samsung Galaxy Buds FE', 15000000, 'بیسیم | Vietnam', '/assets/images/budsfe.webp', 'accessory', 'اقتصادی', '["سفید","مشکی"]', '[]', '[]', 'Vietnam') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=62 (source data.js lines 781-793)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (62, 'PlayStation 5 (Slim)', 320000000, 'Digital Edition | EU', '/assets/images/ps5slim.webp', 'console', 'پرفروش', '["سفید"]', '["825GB"]', '["16GB"]', 'EU') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=63 (source data.js lines 794-806)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (63, 'PlayStation 5 (Standard)', 350000000, 'UHD | US', '/assets/images/ps5standard.webp', 'console', '', '["سفید","مشکی"]', '["825GB"]', '["16GB"]', 'US') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=64 (source data.js lines 807-819)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (64, 'Xbox Series X', 310000000, '1TB | Global', '/assets/images/xboxseriesx.webp', 'console', '', '["مشکی"]', '["1TB"]', '["16GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=65 (source data.js lines 820-832)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (65, 'Xbox Series S', 190000000, '512GB | Global', '/assets/images/xboxseriess.webp', 'console', '', '["سفید","مشکی"]', '["512GB","1TB"]', '["10GB"]', 'Global') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=66 (source data.js lines 833-845)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (66, 'Nintendo Switch OLED', 180000000, 'OLED | JP', '/assets/images/switcholed.webp', 'console', '', '["سفید","آبی","قرمز"]', '["64GB"]', '["4GB"]', 'JP') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
-- record id=67 (source data.js lines 846-858)
INSERT INTO `products` (`id`, `name`, `price`, `spec`, `image`, `category`, `badge`, `colors`, `storage_options`, `ram_options`, `region`) VALUES (67, 'Nintendo Switch Lite', 120000000, 'Lite | EU', '/assets/images/switchlite.webp', 'console', 'اقتصادی', '["زرد","سبز","صورتی"]', '["32GB"]', '["4GB"]', 'EU') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `price` = VALUES(`price`), `spec` = VALUES(`spec`), `image` = VALUES(`image`), `category` = VALUES(`category`), `badge` = VALUES(`badge`), `colors` = VALUES(`colors`), `storage_options` = VALUES(`storage_options`), `ram_options` = VALUES(`ram_options`), `region` = VALUES(`region`);
COMMIT;
